clang-tidy: remove unused fields, keep ctor ABI
Clang-tidy flagged objServer/systemBus as unused private fields in
bios_config_pwd::Password. These members were originally added for
future D-Bus integration but are not referenced today.

To keep the code clean and satisfy -Werror without hacks, remove the
unused members while preserving the constructor signature
(objectServer, systemBus, persistPath) for ABI compatibility with
upstream main.cpp and potential future use.

fixed below errors

'''
In file included from ../src/password.cpp:16:
../include/password.hpp:93:37: error: private field 'objServer' is not used [-Werror,-Wunused-private-field]
   93 |     sdbusplus::asio::object_server& objServer;
      |                                     ^
../include/password.hpp:94:51: error: private field 'systemBus' is not used [-Werror,-Wunused-private-field]
   94 |     std::shared_ptr<sdbusplus::asio::connection>& systemBus;
      |                                                   ^
'''

Change-Id: Id5032b28ccc14ccea4b790dc38cc1e470a33b4e3
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>